# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageBBS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageBBS
  pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire.git"
  pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git"
  pod 'Alamofire-SwiftyJSON', :git => "https://github.com/SwiftyJSON/Alamofire-SwiftyJSON.git"

  target 'ImageBBSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageBBSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
